hunter_config(Caffe VERSION ${HUNTER_Caffe_VERSION} CONFIGURATION_TYPES ${CMAKE_BUILD_TYPE})
hunter_config(RocksDB VERSION ${HUNTER_rocksdb_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(LZ4 VERSION ${HUNTER_lz4_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)