# ---[ BLAS
if(NOT APPLE)
    set(BLAS "Open" CACHE STRING "Selected BLAS library")
    set_property(CACHE BLAS PROPERTY STRINGS "Atlas;Open;MKL")

    if(BLAS STREQUAL "Atlas" OR BLAS STREQUAL "atlas")
        find_package(Atlas REQUIRED)
        include_directories(SYSTEM ${Atlas_INCLUDE_DIR})
        list(APPEND Caffe_LINKER_LIBS ${Atlas_LIBRARIES})
    elseif(BLAS STREQUAL "Open" OR BLAS STREQUAL "open")
        find_package(OpenBLAS)
        if (OpenBLAS_FOUND)
            message("Find OpenBLAS in system")
            list(APPEND Caffe_LINKER_LIBS ${OpenBLAS_LIB})
        else()
            hunter_add_package(OpenBLAS)
            find_package(OpenBLAS CONFIG REQUIRED)
            list(APPEND Caffe_LINKER_LIBS OpenBLAS::OpenBLAS)
        endif ()
    elseif(BLAS STREQUAL "MKL" OR BLAS STREQUAL "mkl")
        find_package(MKL REQUIRED)
        include_directories(SYSTEM ${MKL_INCLUDE_DIR})
        list(APPEND Caffe_LINKER_LIBS ${MKL_LIBRARIES})
        add_definitions(-DUSE_MKL)
    endif()
elseif(APPLE)
    find_package(vecLib REQUIRED)
    include_directories(SYSTEM ${vecLib_INCLUDE_DIR})
    list(APPEND Caffe_LINKER_LIBS ${vecLib_LINKER_LIBS})

    if(VECLIB_FOUND)
        if(NOT vecLib_INCLUDE_DIR MATCHES "^/System/Library/Frameworks/vecLib.framework.*")
            list(APPEND Caffe_DEFINITIONS -DUSE_ACCELERATE)
        endif()
    endif()
endif()