name: main-branch-pm-build

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependency
      run: sudo apt-get install autoconf automake libtool curl make g++ unzip protobuf-compiler libgoogle-glog-dev libboost-all-dev liblz4-dev librocksdb-dev libssl-dev libopenblas-dev libleveldb-dev libsnappy-dev libprotobuf-dev
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}
      
